### ISSUE TITLE
Create Document Status Listing screen

### ISSUE THREAD

**Issue by StanleySathler** [ss-javascript/document-status-manager#2]
It is the first and main screen. Basically, it lists all registered document status.

It must have the following features:

1. A Floating Action Button which allows the user to create a new document status;
2. A list containing all registered document status;
3. A search bar, so the user can search for a specific status;
4. A "load more" button, in case there are too many records.

The design must follow the one posted on README (`master` branch).

Depends on:
- [x] #1 - Implement Redux
- [x] #6 - Add FloatingActionButton component 
- [x] #8 - Add pagination support
- [x] #9 - Add Search component and integrate it to ContentBox
